#--------------------------------------------------------
# Makefile for GCC
# 
# NOTE:  BE SURE TO USE A TAB (not 8 spaces) for all
# sections!
#--------------------------------------------------------

CC=gcc
CFLAGS=-g -D__USE_FIXED_PROTOTYPES__ -ansi

#
# Compiler flags:
#
#  -g 				Enable debugging
#  -ansi 			Don't use GNU extensions.  Stick with ANSI C.
#  -D__USE_FIXED_PROTOTYPES__	Force the compiler to use correct headers

8-6:  8-6.c
	$(CC) $(CFLAGS) -o 11-4 11-4.c

clean:
	rm -f 11-4
